from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List, Optional
import os
from app.database.connection import get_db
from app.database.models import User, Report, ChatHistory
from app.routes.auth import get_current_user
from app.services.pdf_service import pdf_service

router = APIRouter(prefix="/reports", tags=["PDF Reports"])

class ReportRequest(BaseModel):
    session_id: str
    report_type: str = "citizen_legal_advice"

@router.post("/generate")
def generate_pdf_report(req: ReportRequest, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    history = db.query(ChatHistory).filter(ChatHistory.session_id == req.session_id).order_by(ChatHistory.created_at.asc()).all()
    
    if history:
        user_query = history[0].content
        last_assistant_msg = next((h for h in reversed(history) if h.role == "assistant"), None)
        response_text = last_assistant_msg.content if last_assistant_msg else "General Legal Advice"
        citations = last_assistant_msg.citations if last_assistant_msg and last_assistant_msg.citations else []
    else:
        user_query = "Legal Intelligence Summary Report"
        response_text = "Comprehensive legal guidance generated by LegalIQ AI platform."
        citations = []

    pdf_path = pdf_service.generate_legal_report(
        user_name=current_user.full_name or "Valued Client",
        query=user_query,
        response_text=response_text,
        citations=citations,
        action_steps=[
            {"step_number": 1, "title": "Evidence Verification", "description": "Assemble physical & digital evidence (contracts, receipts, communications)."},
            {"step_number": 2, "title": "Statutory Notice", "description": "Issue formal legal notice demanding compliance within 15 days."},
            {"step_number": 3, "title": "Forum Filing", "description": "Approach competent tribunal or police station with legal representation."}
        ],
        report_type=req.report_type
    )

    report_record = Report(
        user_id=current_user.id,
        title=f"Legal Report - {user_query[:30]}",
        report_type=req.report_type,
        file_path=pdf_path,
        content_summary=response_text[:200]
    )
    db.add(report_record)
    db.commit()
    db.refresh(report_record)

    return {
        "report_id": report_record.id,
        "title": report_record.title,
        "download_url": f"/api/v1/reports/download/{report_record.id}"
    }

@router.get("/download/{report_id}")
def download_report(report_id: int, db: Session = Depends(get_db)):
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report or not os.path.exists(report.file_path):
        raise HTTPException(status_code=404, detail="Report file not found.")
    
    return FileResponse(
        report.file_path,
        media_type="application/pdf",
        filename=f"LegalIQ_Advice_Report_{report_id}.pdf"
    )
